/// Creative disciplines Kael case studies can specialize for.
enum CreativeField {
  uiUxDesign,
  interiorDesign,
  graphicDesign,
  photography,
  fashionDesign,
  architecture,
  illustration,
  motionDesign,
  filmVideo,
  productDesign,
  fineArt,
  generalCreative,
}

class FieldProfile {
  final CreativeField field;
  final String displayName;
  final String disciplineBrief;
  final String researchLens;
  final String ideationLens;
  final String creationLens;
  final String refinementLens;
  final String deliveryLens;
  final List<String> vocabulary;
  final String problemFraming;
  final String decisionFocus;
  final String resultsFocus;

  const FieldProfile({
    required this.field,
    required this.displayName,
    required this.disciplineBrief,
    required this.researchLens,
    required this.ideationLens,
    required this.creationLens,
    required this.refinementLens,
    required this.deliveryLens,
    required this.vocabulary,
    required this.problemFraming,
    required this.decisionFocus,
    required this.resultsFocus,
  });

  static FieldProfile forField(CreativeField field) => _profiles[field]!;

  static const _profiles = {
    CreativeField.uiUxDesign: FieldProfile(
      field: CreativeField.uiUxDesign,
      displayName: 'UI/UX & Product Design',
      disciplineBrief:
          'Digital product design focused on user flows, usability, accessibility, and interface systems.',
      researchLens: 'User research, journey mapping, competitive audits, heuristic evaluation, analytics',
      ideationLens: 'Wireframes, user flows, information architecture, design sprints, concept testing',
      creationLens: 'High-fidelity UI, design systems, component libraries, interactive prototypes',
      refinementLens: 'Usability testing iterations, A/B learnings, accessibility passes, dev handoff polish',
      deliveryLens: 'Shipped product outcomes, adoption metrics, task success, stakeholder alignment',
      vocabulary: ['users', 'flows', 'wireframes', 'Figma', 'accessibility', 'conversion', 'onboarding'],
      problemFraming: 'user pain points, business constraints, and product context',
      decisionFocus: 'typography, layout hierarchy, interaction patterns, and design system choices',
      resultsFocus: 'usability improvements, engagement, task completion, and product impact',
    ),
    CreativeField.interiorDesign: FieldProfile(
      field: CreativeField.interiorDesign,
      displayName: 'Interior & Spatial Design',
      disciplineBrief:
          'Spatial design balancing function, atmosphere, materiality, lighting, and client lifestyle.',
      researchLens: 'Site analysis, client brief, mood boards, spatial constraints, building codes, lifestyle audit',
      ideationLens: 'Space planning, zoning, concept boards, material palettes, lighting schemes',
      creationLens: '3D visualization, furniture selection, custom joinery, color and texture composition',
      refinementLens: 'Client feedback rounds, detailing, specification refinement, contractor coordination',
      deliveryLens: 'Installed space, client satisfaction, spatial function, photographic documentation',
      vocabulary: ['spatial', 'materials', 'lighting', 'floor plan', 'mood board', 'ff&e', 'ambience'],
      problemFraming: 'spatial constraints, client needs, and environmental context',
      decisionFocus: 'material selection, lighting layers, furniture scale, circulation, and atmosphere',
      resultsFocus: 'spatial transformation, client outcomes, and functional improvements',
    ),
    CreativeField.graphicDesign: FieldProfile(
      field: CreativeField.graphicDesign,
      displayName: 'Graphic & Brand Design',
      disciplineBrief: 'Visual communication through brand identity, layout, typography, and campaign systems.',
      researchLens: 'Brand audit, audience research, competitive landscape, brief analysis',
      ideationLens: 'Concept exploration, mood boards, sketching, style tiles, naming directions',
      creationLens: 'Logo systems, typographic hierarchy, layout grids, brand guidelines, campaign assets',
      refinementLens: 'Client revisions, print/digital proofing, consistency passes across touchpoints',
      deliveryLens: 'Launch-ready brand system, campaign rollout, client approval, measurable brand lift',
      vocabulary: ['brand', 'identity', 'typography', 'grid', 'campaign', 'visual language', 'guidelines'],
      problemFraming: 'communication goals, audience, and brand positioning gaps',
      decisionFocus: 'typographic pairing, color systems, layout rhythm, and visual metaphor',
      resultsFocus: 'brand recognition, campaign performance, and client adoption of the system',
    ),
    CreativeField.photography: FieldProfile(
      field: CreativeField.photography,
      displayName: 'Photography',
      disciplineBrief: 'Visual storytelling through composition, lighting, direction, and post-production.',
      researchLens: 'Subject research, location scouting, mood references, technical constraints',
      ideationLens: 'Shot lists, storyboards, lighting plans, styling direction, concept boards',
      creationLens: 'Shoot execution, lens choice, lighting setup, direction, capture workflow',
      refinementLens: 'Culling, retouching, color grading, sequencing, print/web optimization',
      deliveryLens: 'Final gallery, client delivery, exhibition, publication, or campaign usage',
      vocabulary: ['composition', 'lighting', 'exposure', 'color grade', 'series', 'narrative', 'lens'],
      problemFraming: 'visual brief, subject context, and creative constraints',
      decisionFocus: 'framing, lighting mood, color treatment, and narrative sequencing',
      resultsFocus: 'client outcomes, series cohesion, and audience response',
    ),
    CreativeField.fashionDesign: FieldProfile(
      field: CreativeField.fashionDesign,
      displayName: 'Fashion Design',
      disciplineBrief: 'Garment and collection design from concept through construction and presentation.',
      researchLens: 'Trend research, fabric sourcing, body/form studies, cultural references',
      ideationLens: 'Sketching, draping concepts, silhouette exploration, collection theming',
      creationLens: 'Pattern development, sampling, construction, lookbook styling',
      refinementLens: 'Fit sessions, material adjustments, collection editing, presentation polish',
      deliveryLens: 'Collection launch, runway/showcase, retail readiness, press coverage',
      vocabulary: ['silhouette', 'collection', 'fabric', 'drape', 'construction', 'lookbook', 'runway'],
      problemFraming: 'collection brief, market positioning, and wearer needs',
      decisionFocus: 'silhouette, fabric, construction technique, and collection narrative',
      resultsFocus: 'collection reception, wearability, and brand alignment',
    ),
    CreativeField.architecture: FieldProfile(
      field: CreativeField.architecture,
      displayName: 'Architecture',
      disciplineBrief: 'Built environment design integrating structure, program, context, and sustainability.',
      researchLens: 'Site analysis, program requirements, zoning, climate, precedent studies',
      ideationLens: 'Massing studies, schematic design, spatial organization, concept models',
      creationLens: 'Design development, drawings, material specification, 3D visualization',
      refinementLens: 'Code compliance, consultant coordination, detail refinement, value engineering',
      deliveryLens: 'Built outcome, occupancy, sustainability performance, user experience of space',
      vocabulary: ['site', 'program', 'massing', 'structure', 'facade', 'sustainability', 'context'],
      problemFraming: 'site constraints, program needs, and contextual forces',
      decisionFocus: 'form, materiality, circulation, environmental response, and structural logic',
      resultsFocus: 'built performance, user experience, and contextual integration',
    ),
    CreativeField.illustration: FieldProfile(
      field: CreativeField.illustration,
      displayName: 'Illustration',
      disciplineBrief: 'Narrative and editorial illustration with distinct visual voice and medium mastery.',
      researchLens: 'Brief analysis, reference gathering, style research, audience context',
      ideationLens: 'Thumbnails, concept sketches, style exploration, narrative planning',
      creationLens: 'Finished illustration, medium execution, color, line, and composition',
      refinementLens: 'Art direction feedback, revision passes, file preparation for print/digital',
      deliveryLens: 'Published work, client approval, series completion, audience engagement',
      vocabulary: ['narrative', 'style', 'medium', 'composition', 'character', 'editorial', 'series'],
      problemFraming: 'story, audience, and visual communication goals',
      decisionFocus: 'style, composition, color palette, and narrative clarity',
      resultsFocus: 'client satisfaction, narrative impact, and visual distinctiveness',
    ),
    CreativeField.motionDesign: FieldProfile(
      field: CreativeField.motionDesign,
      displayName: 'Motion & Animation Design',
      disciplineBrief: 'Time-based design for animation, motion graphics, and kinetic brand systems.',
      researchLens: 'Brief analysis, reference reels, audience platform research, technical specs',
      ideationLens: 'Storyboards, animatics, style frames, motion tests, timing exploration',
      creationLens: 'Animation production, keyframes, easing, compositing, sound sync',
      refinementLens: 'Timing polish, render optimization, client review cycles, format exports',
      deliveryLens: 'Final motion deliverables, campaign launch, platform performance',
      vocabulary: ['keyframes', 'timing', 'easing', 'storyboard', 'motion system', 'animatic', 'render'],
      problemFraming: 'narrative goals, platform constraints, and brand motion language',
      decisionFocus: 'timing, easing, visual style, and motion hierarchy',
      resultsFocus: 'engagement metrics, brand consistency, and delivery quality',
    ),
    CreativeField.filmVideo: FieldProfile(
      field: CreativeField.filmVideo,
      displayName: 'Film & Video',
      disciplineBrief: 'Cinematic storytelling through direction, cinematography, editing, and post-production.',
      researchLens: 'Script analysis, location scouting, reference films, production planning',
      ideationLens: 'Shot listing, storyboarding, treatment writing, visual tone development',
      creationLens: 'Production, cinematography, direction, sound recording, editing',
      refinementLens: 'Color grade, sound mix, pacing edits, VFX integration',
      deliveryLens: 'Final cut, festival/client delivery, distribution, audience reception',
      vocabulary: ['cinematography', 'edit', 'color grade', 'narrative', 'production', 'sound design'],
      problemFraming: 'story goals, production constraints, and audience',
      decisionFocus: 'shot language, pacing, color mood, and sound design',
      resultsFocus: 'audience impact, festival/client outcomes, and narrative clarity',
    ),
    CreativeField.productDesign: FieldProfile(
      field: CreativeField.productDesign,
      displayName: 'Industrial & Product Design',
      disciplineBrief: 'Physical product design from user need through prototyping and manufacturing.',
      researchLens: 'User needs, ergonomics, market analysis, manufacturing constraints',
      ideationLens: 'Sketching, CAD exploration, form studies, prototyping concepts',
      creationLens: 'CAD modeling, prototyping, material selection, CMF decisions',
      refinementLens: 'User testing, engineering collaboration, DFM iterations, tooling prep',
      deliveryLens: 'Manufactured product, user validation, market launch outcomes',
      vocabulary: ['ergonomics', 'CMF', 'prototype', 'CAD', 'manufacturing', 'form', 'usability'],
      problemFraming: 'user needs, manufacturing constraints, and market context',
      decisionFocus: 'form, material, ergonomics, and manufacturing feasibility',
      resultsFocus: 'user validation, production success, and market impact',
    ),
    CreativeField.fineArt: FieldProfile(
      field: CreativeField.fineArt,
      displayName: 'Fine Art',
      disciplineBrief: 'Studio art practice exploring concept, medium, and exhibition context.',
      researchLens: 'Concept development, art historical context, material exploration, studio research',
      ideationLens: 'Sketching, maquettes, process experiments, series planning',
      creationLens: 'Work production, medium mastery, scale and material decisions',
      refinementLens: 'Critique response, series editing, presentation preparation',
      deliveryLens: 'Exhibition, collection, critical reception, artistic statement',
      vocabulary: ['concept', 'medium', 'series', 'process', 'exhibition', 'critique', 'studio'],
      problemFraming: 'conceptual framework, artistic intent, and context',
      decisionFocus: 'medium, scale, composition, and conceptual clarity',
      resultsFocus: 'exhibition outcomes, critical response, and artistic development',
    ),
    CreativeField.generalCreative: FieldProfile(
      field: CreativeField.generalCreative,
      displayName: 'Creative Practice',
      disciplineBrief: 'Cross-disciplinary creative work spanning research through delivery.',
      researchLens: 'Context gathering, stakeholder interviews, reference analysis, constraints mapping',
      ideationLens: 'Concept exploration, brainstorming, prototyping directions, creative brief alignment',
      creationLens: 'Execution of the core creative work across chosen media',
      refinementLens: 'Iteration cycles, feedback integration, quality passes',
      deliveryLens: 'Final deliverables, client/stakeholder outcomes, project impact',
      vocabulary: ['concept', 'iteration', 'craft', 'audience', 'deliverable', 'creative direction'],
      problemFraming: 'project constraints, audience, and creative goals',
      decisionFocus: 'creative choices aligned to the project brief and medium',
      resultsFocus: 'project outcomes, learnings, and impact',
    ),
  };
}
